<?php

namespace Database\Seeders;

use App\Models\SdRegistration;
use Illuminate\Database\Seeder;

class SdRegistrationSeeder extends Seeder
{
    public function run()
    {
        SdRegistration::create([
            'user_id' => '22',
            'unique_code' => 'vtp3wDE2AX3YIJssTcUA',
            'registration_code' => '2324201001',
            'virtual_code' => '8947802324201001',
            'registration_path' => 'External',
            'full_name' => 'Aras Ramaniya Mulyana',
            'nick_name' => 'Aras',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-08-18',
            'origin_school' => 'Tk Santo Yusup 1',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Suryaman Mulyana',
            'parent_phone' => '087829555563',
            'parent_email' => 'Artmanreborn@gmail.com',
            'payment_proof' => '1659420959.png',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 06:16:00',
            'updated_at' => '2022-08-02 06:16:00'
        ]);

        SdRegistration::create([
            'user_id' => '23',
            'unique_code' => 'eNs1F9gq4ktT9vlZ51Tv',
            'registration_code' => '2324201002',
            'virtual_code' => '8947802324201002',
            'registration_path' => 'External',
            'full_name' => 'Teresa Olivia Prameswari',
            'nick_name' => 'Olivia',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-11-01',
            'origin_school' => 'Tk Generasi Unggul Antapani',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Fransiska Ineke Airin',
            'parent_phone' => '081805151202',
            'parent_email' => 'reginaxyla@gmail.com',
            'payment_proof' => '1659421074.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 06:17:54',
            'updated_at' => '2022-08-02 06:17:54'
        ]);

        SdRegistration::create([
            'user_id' => '24',
            'unique_code' => 'iXrT1pZ1zkiN5MF5EesF',
            'registration_code' => '2324201003',
            'virtual_code' => '8947802324201003',
            'registration_path' => 'Internal',
            'full_name' => 'Charlotte Heidi Djaya Siswaja',
            'nick_name' => 'Heidi',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-04-04',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Stephanie Setiawatti',
            'parent_phone' => '081910260967',
            'parent_email' => 'stephanie.setiawati@gmail.com',
            'payment_proof' => '1659422515.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 06:41:50',
            'updated_at' => '2022-08-02 06:41:50'
        ]);

        SdRegistration::create([
            'user_id' => '25',
            'unique_code' => 'uAcs4mcrWZZhmb6U6Ks4',
            'registration_code' => '2324201004',
            'virtual_code' => '8947802324201004',
            'registration_path' => 'Internal',
            'full_name' => 'Charlotte Heidi Djaya Siswaja',
            'nick_name' => 'Heidi',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-04-04',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Stephanie Setiawatti',
            'parent_phone' => '081910260967',
            'parent_email' => 'stephanie.setiawati@gmail.com',
            'payment_proof' => '1659422516.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 06:41:56',
            'updated_at' => '2022-08-02 06:41:56'
        ]);

        SdRegistration::create([
            'user_id' => '26',
            'unique_code' => 'NQCfg22DTE853EEI9PdS',
            'registration_code' => '2324201005',
            'virtual_code' => '8947802324201005',
            'registration_path' => 'External',
            'full_name' => 'Keenan Lemuel Noya Kurniadi',
            'nick_name' => 'Keenan',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-10-02',
            'origin_school' => 'Tk Santo Agustinus',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Noviyani',
            'parent_phone' => '085314705969',
            'parent_email' => 'noviyanioppie@gmail.com',
            'payment_proof' => '1659423204.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 06:53:24',
            'updated_at' => '2022-08-12 07:27:30'
        ]);

        SdRegistration::create([
            'user_id' => '27',
            'unique_code' => 'ha6MN8hloxz61QbgoEGE',
            'registration_code' => '2324201006',
            'virtual_code' => '8947802324201006',
            'registration_path' => 'Internal',
            'full_name' => 'Sean Sebastianus',
            'nick_name' => 'Sean',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-07-19',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Mei',
            'parent_phone' => '087870060068',
            'parent_email' => 'Meii_21@gmail.com',
            'payment_proof' => '1659423291.png',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 06:54:51',
            'updated_at' => '2022-08-02 06:54:51'
        ]);

        SdRegistration::create([
            'user_id' => '28',
            'unique_code' => 'mOB1N9zlqoHi8fj7Teab',
            'registration_code' => '2324201007',
            'virtual_code' => '8947802324201007',
            'registration_path' => 'Internal',
            'full_name' => 'Richard Avsalom Napitupulu',
            'nick_name' => 'Richard',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-11-02',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Runia Putri Utami',
            'parent_phone' => '082217311178',
            'parent_email' => 'runiaputri78@gmail.com',
            'payment_proof' => '1659424409.png',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 07:13:29',
            'updated_at' => '2022-08-08 03:49:15'
        ]);

        SdRegistration::create([
            'user_id' => '29',
            'unique_code' => 'J4xr5bh5idDCnWDjhQP3',
            'registration_code' => '2324201008',
            'virtual_code' => '8947802324201008',
            'registration_path' => 'External',
            'full_name' => 'Daviandra Mikail Kaivan',
            'nick_name' => 'Dave',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-03-27',
            'origin_school' => 'Tk Tunas Cendekia Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Ceyla',
            'parent_phone' => '081322347200',
            'parent_email' => 'ceylacahyadi@gmail.com',
            'payment_proof' => '1659426290.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 07:44:50',
            'updated_at' => '2022-08-02 07:44:50'
        ]);

        SdRegistration::create([
            'user_id' => '30',
            'unique_code' => 'CwsgonfQ24E1aPMEb7Mr',
            'registration_code' => '2324201009',
            'virtual_code' => '8947802324201009',
            'registration_path' => 'Internal',
            'full_name' => 'Gregorius Trikasih Bhadra',
            'nick_name' => 'Bhadra',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-08-28',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Rosalia Hari Sakti P',
            'parent_phone' => '081223559169',
            'parent_email' => 'rosaliahsp@gmail.com',
            'payment_proof' => '1659443821.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 12:37:01',
            'updated_at' => '2022-08-02 12:37:01'
        ]);

        SdRegistration::create([
            'user_id' => '31',
            'unique_code' => 'uzdKC7OhTuBEXH2GN4Oi',
            'registration_code' => '2324201010',
            'virtual_code' => '8947802324201010',
            'registration_path' => 'Internal',
            'full_name' => 'Avellino Djenar Rasendriya',
            'nick_name' => 'Djenar',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-08-31',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Andreas Grandis Kurniawan',
            'parent_phone' => '0811663939',
            'parent_email' => 'grandis.andreas@gmail.com',
            'payment_proof' => '1659483172.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 23:32:52',
            'updated_at' => '2022-08-02 23:32:52'
        ]);

        SdRegistration::create([
            'user_id' => '32',
            'unique_code' => 'g3CEbSl25Sp0ZOFZ53a4',
            'registration_code' => '2324201011',
            'virtual_code' => '8947802324201011',
            'registration_path' => 'Internal',
            'full_name' => 'Nayla Zivana Tampubolon',
            'nick_name' => 'Zivana',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-05-30',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Surya Tetty',
            'parent_phone' => '081223835552',
            'parent_email' => 'surya.bdg111@gmail.com',
            'payment_proof' => '1659494829.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-03 02:47:09',
            'updated_at' => '2022-08-03 02:47:09'
        ]);

        SdRegistration::create([
            'user_id' => '33',
            'unique_code' => '6zeZPHRQqsfyPOsrb4OU',
            'registration_code' => '2324201012',
            'virtual_code' => '8947802324201012',
            'registration_path' => 'Internal',
            'full_name' => 'Anna Caritas Illarya Anunu',
            'nick_name' => 'Illarya',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-01-15',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Angela Yunita Dosiwoda - Abraham Aprilino Anunu',
            'parent_phone' => '081221598424',
            'parent_email' => 'angelayunita.dw@gmail.com',
            'payment_proof' => '1659498286.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-03 03:44:47',
            'updated_at' => '2022-08-03 03:44:47'
        ]);

        SdRegistration::create([
            'user_id' => '34',
            'unique_code' => 'Ofp1sMHwRJFjaBi8S4ke',
            'registration_code' => '2324201013',
            'virtual_code' => '8947802324201013',
            'registration_path' => 'Internal',
            'full_name' => 'Lucassie Galen Indarto',
            'nick_name' => 'Galen',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-10-28',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Yoanne Sukoco',
            'parent_phone' => '085715738680',
            'parent_email' => 'yoanneens@gmail.com',
            'payment_proof' => '1659504002.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-03 05:20:02',
            'updated_at' => '2022-08-03 05:20:02'
        ]);

        SdRegistration::create([
            'user_id' => '35',
            'unique_code' => 'lPoVM3Xs1KTw3aZlk9qE',
            'registration_code' => '2324201014',
            'virtual_code' => '8947802324201014',
            'registration_path' => 'External',
            'full_name' => 'Mikaela Holy Sinta Putriditya',
            'nick_name' => 'Holy',
            'birth_town' => 'Semarang',
            'birth_date' => '2016-12-03',
            'origin_school' => 'Tk Santo Agustinus',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Fransiska Irmawati',
            'parent_phone' => '0895332301896',
            'parent_email' => 'fransiska.irmawati.fi@gmail.com',
            'payment_proof' => '1659517890.png',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-03 09:11:30',
            'updated_at' => '2022-08-08 03:55:10'
        ]);

        SdRegistration::create([
            'user_id' => '36',
            'unique_code' => 'Z4Wffx4J7Ul7tFMRMwH2',
            'registration_code' => '2324201015',
            'virtual_code' => '8947802324201015',
            'registration_path' => 'External',
            'full_name' => 'Eowyn Felicity Nattaya Budiono',
            'nick_name' => 'Eowyn',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-08-14',
            'origin_school' => 'Tk St Melania',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Gerardy Putrama Budiono',
            'parent_phone' => '089501144777',
            'parent_email' => 'gerryizme@yahoo.co.id',
            'payment_proof' => '1659521568.png',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-03 10:12:48',
            'updated_at' => '2022-08-03 10:12:48'
        ]);

        SdRegistration::create([
            'user_id' => '37',
            'unique_code' => '61xRn93FsoBPyx4YqFKA',
            'registration_code' => '2324201016',
            'virtual_code' => '8947802324201016',
            'registration_path' => 'Internal',
            'full_name' => 'Johan Tristan Wattimena',
            'nick_name' => 'Johan',
            'birth_town' => 'Bandung',
            'birth_date' => '2015-08-12',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Law Krisnawati',
            'parent_phone' => '08122068587',
            'parent_email' => 'Krisnawatiwattimena@gmail.com',
            'payment_proof' => '1659662028.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-05 01:13:48',
            'updated_at' => '2022-08-12 07:12:46'
        ]);

        SdRegistration::create([
            'user_id' => '38',
            'unique_code' => 'LMplhfmh7YN1NkMAof60',
            'registration_code' => '2324201017',
            'virtual_code' => '8947802324201017',
            'registration_path' => 'External',
            'full_name' => 'Yosua Kenzie Setiawan',
            'nick_name' => 'Kenzie',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-08-25',
            'origin_school' => 'Tk Santo Agustinus',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Agnes',
            'parent_phone' => '082215244155',
            'parent_email' => 'agneslie82@yahoo.com',
            'payment_proof' => '1659662862.pmg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-05 01:27:42',
            'updated_at' => '2022-08-05 01:27:42'
        ]);

        SdRegistration::create([
            'user_id' => '39',
            'unique_code' => 'aYxLYLvqGjYzT6Bj7t2t',
            'registration_code' => '2324201018',
            'virtual_code' => '8947802324201018',
            'registration_path' => 'Internal',
            'full_name' => 'Stefhanie Hedy Putri Haryanto',
            'nick_name' => 'Stefhanie',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-09-14',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Haryanto',
            'parent_phone' => '082128732912',
            'parent_email' => 'Nataliahedy0@gmail.com',
            'payment_proof' => '1659748294.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-06 01:11:34',
            'updated_at' => '2022-08-06 01:11:34'
        ]);

        SdRegistration::create([
            'user_id' => '40',
            'unique_code' => 'ry6qaqz8Ci4BI1hHfnQm',
            'registration_code' => '2324201019',
            'virtual_code' => '8947802324201019',
            'registration_path' => 'Internal',
            'full_name' => 'Carlos Joseph Sinaga',
            'nick_name' => 'Carlos',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-08-09',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Boyke Martinus Sinaga',
            'parent_phone' => '081221220082',
            'parent_email' => 'tenz1610@gmail.com',
            'payment_proof' => '1659762496.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-06 05:08:16',
            'updated_at' => '2022-08-12 07:18:27'
        ]);

        SdRegistration::create([
            'user_id' => '41',
            'unique_code' => '4FgfFjTwk4V1DczXBHsh',
            'registration_code' => '2324201020',
            'virtual_code' => '8947802324201020',
            'registration_path' => 'Internal',
            'full_name' => 'Gabriel Mikaela Hambali',
            'nick_name' => 'Gaby',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-08-14',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Agnes',
            'parent_phone' => '082117720200',
            'parent_email' => 'caliestani@gmail.com',
            'payment_proof' => '1659860120.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-07 08:15:20',
            'updated_at' => '2022-08-07 08:15:20'
        ]);

        SdRegistration::create([
            'user_id' => '42',
            'unique_code' => 'WFQreIgxpZbfwYhEKP5I',
            'registration_code' => '2324201021',
            'virtual_code' => '8947802324201021',
            'registration_path' => 'Internal',
            'full_name' => 'Alicia Karen Santoso',
            'nick_name' => 'Cia',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-02-20',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Sinta Ayu',
            'parent_phone' => '08122008577',
            'parent_email' => 'cinthaayu81@gmail.com',
            'payment_proof' => '1659877083.png',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-07 12:58:03',
            'updated_at' => '2022-08-07 12:58:03'
        ]);

        SdRegistration::create([
            'user_id' => '43',
            'unique_code' => 'Y2VOG9CUdxGTJvWi4D79',
            'registration_code' => '2324201022',
            'virtual_code' => '8947802324201022',
            'registration_path' => 'External',
            'full_name' => 'Gregorius Keenandra Singapraja',
            'nick_name' => 'Keenan',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-09-23',
            'origin_school' => 'Tk St Yusup Cikutra',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Antonius Teddy Setiawan',
            'parent_phone' => '08122084043',
            'parent_email' => 'nani.telkomedika@gmail.com',
            'payment_proof' => '1659921498.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-08 01:18:18',
            'updated_at' => '2022-08-08 04:08:51'
        ]);

        SdRegistration::create([
            'user_id' => '44',
            'unique_code' => 'VkeZV5pnROJNUzCyfaeH',
            'registration_code' => '2324201023',
            'virtual_code' => '8947802324201023',
            'registration_path' => 'Internal',
            'full_name' => 'Mercy Shamarel Tampubolon',
            'nick_name' => 'Mercy',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-09-16',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Reynold Tampubolon',
            'parent_phone' => '081339409460',
            'parent_email' => 'reynoldtamp@gmail.com',
            'payment_proof' => '1659926583.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-08 02:43:03',
            'updated_at' => '2022-08-08 02:43:03'
        ]);

        SdRegistration::create([
            'user_id' => '45',
            'unique_code' => 'J8UASnoYS6QpKpgtfW9o',
            'registration_code' => '2324201024',
            'virtual_code' => '8947802324201024',
            'registration_path' => 'Internal',
            'full_name' => 'Asdasdas',
            'nick_name' => 'Dasda',
            'birth_town' => 'Sdasdasd',
            'birth_date' => '2022-08-02',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Asdasd',
            'parent_phone' => '1244124',
            'parent_email' => 'rangga9@gmail.com',
            'payment_proof' => '1659946317.png',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-08 08:11:58',
            'updated_at' => '2022-08-08 08:11:58'
        ]);

        SdRegistration::create([
            'user_id' => '46',
            'unique_code' => 'rTPg7o9EodJKokHkuQ8u',
            'registration_code' => '2324201025',
            'virtual_code' => '8947802324201025',
            'registration_path' => 'Internal',
            'full_name' => 'Maria Amaya Kamanesha',
            'nick_name' => 'Amaya',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-08-14',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Yosevha Fuzi Suciliawati',
            'parent_phone' => '081320231003',
            'parent_email' => 'yosevhafuzi@gmail.com',
            'payment_proof' => '1659947032.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-08 08:23:52',
            'updated_at' => '2022-08-08 08:23:52'
        ]);

        SdRegistration::create([
            'user_id' => '47',
            'unique_code' => 'o3VS9KYgwYGSGjZXBEgZ',
            'registration_code' => '2324201026',
            'virtual_code' => '8947802324201026',
            'registration_path' => 'Internal',
            'full_name' => 'Irene Naraya Saputro',
            'nick_name' => 'Naya',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-11-21',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Ana Sri Palupi',
            'parent_phone' => '089639834841',
            'parent_email' => 'anna_palupi@yahoo.com',
            'payment_proof' => '1659948509.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-08 08:48:29',
            'updated_at' => '2022-08-08 08:48:29'
        ]);

        SdRegistration::create([
            'user_id' => '48',
            'unique_code' => '2CJfaGx8NoocyrtCbKSu',
            'registration_code' => '2324201027',
            'virtual_code' => '8947802324201027',
            'registration_path' => 'Internal',
            'full_name' => 'Anthony Jovito Christian',
            'nick_name' => 'Jovito',
            'birth_town' => 'Kuningan',
            'birth_date' => '2016-07-02',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Paullina Dwi Christyana',
            'parent_phone' => '08179568778',
            'parent_email' => 'ullinachris@gmail.com',
            'payment_proof' => '1659960023.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-08 12:00:23',
            'updated_at' => '2022-08-08 23:54:48'
        ]);

        SdRegistration::create([
            'user_id' => '49',
            'unique_code' => 'ddw2TxJ5Jz0dftU0MRQx',
            'registration_code' => '2324201028',
            'virtual_code' => '8947802324201028',
            'registration_path' => 'Internal',
            'full_name' => 'Asdsad',
            'nick_name' => 'Asdasd',
            'birth_town' => 'Asdsadas',
            'birth_date' => '2022-08-03',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Asdasdas',
            'parent_phone' => '124124124',
            'parent_email' => 'rangga9@gmail.com',
            'payment_proof' => '1660089263.png',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-09 23:54:24',
            'updated_at' => '2022-08-09 23:54:24'
        ]);

        SdRegistration::create([
            'user_id' => '50',
            'unique_code' => 'LQSRGO85Oy9y3LKO5wVw',
            'registration_code' => '2324201029',
            'virtual_code' => '8947802324201029',
            'registration_path' => 'Internal',
            'full_name' => 'Arnathan Fathir Diardwika',
            'nick_name' => 'Nathan',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-08-28',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Arry Marianne',
            'parent_phone' => '081221295002',
            'parent_email' => 'marin.marianne82@gmail.com',
            'payment_proof' => '1660089768.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-10 00:02:48',
            'updated_at' => '2022-08-10 00:02:48'
        ]);

        SdRegistration::create([
            'user_id' => '51',
            'unique_code' => 'yQqvjfEkK8leEwmv5r1r',
            'registration_code' => '2324201030',
            'virtual_code' => '8947802324201030',
            'registration_path' => 'Internal',
            'full_name' => 'Mattea Kireina Indriani',
            'nick_name' => 'Mattea',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-02-24',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Griasto Bekti',
            'parent_phone' => '085659007714',
            'parent_email' => 'griasto@gmail.com',
            'payment_proof' => '1660121546.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-10 08:52:26',
            'updated_at' => '2022-08-10 08:52:26'
        ]);

        SdRegistration::create([
            'user_id' => '52',
            'unique_code' => 'K7Vkj5dCSqMwsRA2jeLV',
            'registration_code' => '2324201031',
            'virtual_code' => '8947802324201031',
            'registration_path' => 'Internal',
            'full_name' => 'Angelica Grace Revauli',
            'nick_name' => 'Angel',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-05-02',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Maya Indriyani',
            'parent_phone' => '081221797980',
            'parent_email' => 'mayaindriyanis@gmail.com',
            'payment_proof' => '1660128342.png',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-10 10:45:42',
            'updated_at' => '2022-08-10 10:45:42'
        ]);

        SdRegistration::create([
            'user_id' => '53',
            'unique_code' => 'eIYNGsCIYVN6ulbCT4Z5',
            'registration_code' => '2324201032',
            'virtual_code' => '8947802324201032',
            'registration_path' => 'Internal',
            'full_name' => 'Aurelia Nadeline Maheswari',
            'nick_name' => 'Aurel',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-09-11',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Lidwina Alfreda Widyastuti',
            'parent_phone' => '085322522590',
            'parent_email' => 'mpredh99@gmail.com',
            'payment_proof' => '1660177948.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-11 00:32:28',
            'updated_at' => '2022-08-11 00:32:28'
        ]);

        SdRegistration::create([
            'user_id' => '54',
            'unique_code' => 'Ckj5bEoqen86rL5KZS9Q',
            'registration_code' => '2324201033',
            'virtual_code' => '8947802324201033',
            'registration_path' => 'Internal',
            'full_name' => 'Nikolas Habel Hadibarata',
            'nick_name' => 'Habel',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-09-19',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Yohana Fransiska Ferawati',
            'parent_phone' => '085317000718',
            'parent_email' => 'yohana.fera@gmail.com',
            'payment_proof' => '1660267326.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-12 01:22:06',
            'updated_at' => '2022-08-12 01:22:06'
        ]);

        SdRegistration::create([
            'user_id' => '55',
            'unique_code' => 'zVaDvxKGzCFS1kujzfMj',
            'registration_code' => '2324201034',
            'virtual_code' => '8947802324201034',
            'registration_path' => 'External',
            'full_name' => 'Isadora Patricia Siahaan',
            'nick_name' => 'Isadora',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-06-18',
            'origin_school' => 'Tk Santa Melania',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Octarina Gracia Galuhningrum',
            'parent_phone' => '081322498975',
            'parent_email' => 'cia_winnie@yahoo.com',
            'payment_proof' => '1660279856.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-12 04:50:56',
            'updated_at' => '2022-08-12 04:50:56'
        ]);

        SdRegistration::create([
            'user_id' => '56',
            'unique_code' => 'iroKxo1mbVH5187yHnmv',
            'registration_code' => '2324201035',
            'virtual_code' => '8947802324201035',
            'registration_path' => 'External',
            'full_name' => 'Isadora Patricia Siahaan',
            'nick_name' => 'Isadora',
            'birth_town' => 'Bandung',
            'birth_date' => '2017-06-18',
            'origin_school' => 'Tk Santa Melania',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Octarina Gracia Galuhningrum',
            'parent_phone' => '081322498975',
            'parent_email' => 'cia_winnie@yahoo.com',
            'payment_proof' => '1660279859.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-12 04:50:59',
            'updated_at' => '2022-08-12 04:50:59'
        ]);

        SdRegistration::create([
            'user_id' => '57',
            'unique_code' => 'HSIxJFOVoXF1YS7sN2Ww',
            'registration_code' => '2324201036',
            'virtual_code' => '8947802324201036',
            'registration_path' => 'Internal',
            'full_name' => 'Misericordiae Eksha Vidya Pramodana',
            'nick_name' => 'Eksha',
            'birth_town' => 'Bandung',
            'birth_date' => '2016-07-20',
            'origin_school' => 'Tk Santa Ursula Bandung',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Andreas Verdyanto',
            'parent_phone' => '081322959695',
            'parent_email' => 'arthemist83@gmail.com',
            'payment_proof' => '1660385975.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-13 10:19:35',
            'updated_at' => '2022-08-13 10:19:35'
        ]);
    }
}
