<?php

namespace Database\Seeders;

use App\Models\TbtkRegistration;
use Illuminate\Database\Seeder;

class TbtkRegistrationSeeder extends Seeder
{
    public function run()
    {
        TbtkRegistration::create([
            'user_id' => '6',
            'unique_code' => 'VI7RUsrHpu8S3rEcjSuX',
            'registration_code' => '2324101001',
            'virtual_code' => '8947802324101001',
            'full_name' => 'Ezekiel Lumban Tobing',
            'nick_name' => 'Kiel',
            'birth_town' => 'Tangerang',
            'birth_date' => '2020-02-03',
            'origin_school' => '',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Eva Kristina',
            'parent_phone' => '082136773350',
            'parent_email' => 'eva.kristina.naibaho@gmail.com',
            'payment_proof' => '1659435126.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 10:12:06',
            'updated_at' => '2022-08-05 03:28:41'
        ]);

        TbtkRegistration::create([
            'user_id' => '7',
            'unique_code' => 'dUcKOqCwHhPcl6OwNNeC',
            'registration_code' => '2324101002',
            'virtual_code' => '8947802324101002',
            'full_name' => 'Mikhayla Lady Clairine',
            'nick_name' => 'Kakhay',
            'birth_town' => 'Bandung',
            'birth_date' => '2019-01-16',
            'origin_school' => '',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Tirani Susanti',
            'parent_phone' => '081223434363',
            'parent_email' => 'susanuban@gmail.com',
            'payment_proof' => '1659435574.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 10:19:34',
            'updated_at' => '2022-08-05 05:14:42',
            'deleted_at' => '2022-08-11 08:06:47'
        ]);

        TbtkRegistration::create([
            'user_id' => '8',
            'unique_code' => 'S4CP8WwS3IVb3rzpAIPW',
            'registration_code' => '2324102001',
            'virtual_code' => '8947802324102001',
            'full_name' => 'Kevin Jericho Noya Kurniadi',
            'nick_name' => 'Kevin',
            'birth_town' => 'Bandung',
            'birth_date' => '2018-09-11',
            'origin_school' => '',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '2',
            'parent_name' => 'Noviyani',
            'parent_phone' => '085318444346',
            'parent_email' => 'noviyanioppie@gmail.com',
            'payment_proof' => '1659436358.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 10:32:38',
            'updated_at' => '2022-08-05 03:33:40'
        ]);

        TbtkRegistration::create([
            'user_id' => '9',
            'unique_code' => 'rcBjssPb21xf2WkQwLYO',
            'registration_code' => '2324102002',
            'virtual_code' => '8947802324102002',
            'full_name' => 'Mikhayla Lady Clairine',
            'nick_name' => 'Kakhay',
            'birth_town' => 'Bandung',
            'birth_date' => '2019-01-16',
            'origin_school' => '',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '2',
            'parent_name' => 'Tirani Susanti',
            'parent_phone' => '081223434363',
            'parent_email' => 'susanuban@gmail.com',
            'payment_proof' => '1659436390.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 10:33:10',
            'updated_at' => '2022-08-05 05:14:50',
            'deleted_at' => '2022-08-11 08:06:27'
        ]);

        TbtkRegistration::create([
            'user_id' => '10',
            'unique_code' => '4VsC7sWHiSDhqtVZBzwo',
            'registration_code' => '2324102003',
            'virtual_code' => '8947802324102003',
            'full_name' => 'Christian David',
            'nick_name' => 'David',
            'birth_town' => 'Ciamis',
            'birth_date' => '2019-03-09',
            'origin_school' => '',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '2',
            'parent_name' => 'Lusiana Mirawati',
            'parent_phone' => '083822800372',
            'parent_email' => 'lucianamirawati@gmail.com',
            'payment_proof' => '1659436429.png',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 10:33:49',
            'updated_at' => '2022-08-05 03:29:29'
        ]);

        TbtkRegistration::create([
            'user_id' => '11',
            'unique_code' => 'bQLkDQzagHrJVfCbq7pu',
            'registration_code' => '2324102004',
            'virtual_code' => '8947802324102004',
            'full_name' => 'Mikhayla Lady Clairine',
            'nick_name' => 'Kakhay',
            'birth_town' => 'Bandung',
            'birth_date' => '2019-01-16',
            'origin_school' => '',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '2',
            'parent_name' => 'Tirani Susanti',
            'parent_phone' => '081223434363',
            'parent_email' => 'susanuban@gmail.com',
            'payment_proof' => '1659436829.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 10:40:29',
            'updated_at' => '2022-08-02 10:40:29'
        ]);

        TbtkRegistration::create([
            'user_id' => '12',
            'unique_code' => 'LXb7Ec9P1ufP4VUIzNHw',
            'registration_code' => '2324102005',
            'virtual_code' => '8947802324102005',
            'full_name' => 'Gisella Shinejoan Sujono',
            'nick_name' => 'Shine',
            'birth_town' => 'Bandung',
            'birth_date' => '2018-05-26',
            'origin_school' => '',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '2',
            'parent_name' => 'Anastasia Maria',
            'parent_phone' => '081808220050',
            'parent_email' => 'anast.sujono@gmail.com',
            'payment_proof' => '1659442716.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-02 12:18:39',
            'updated_at' => '2022-08-02 12:18:39'
        ]);

        TbtkRegistration::create([
            'user_id' => '13',
            'unique_code' => 'bMN3sity2WVu479jsldz',
            'registration_code' => '2324102006',
            'virtual_code' => '8947802324102006',
            'full_name' => 'Gianna Clarissa Ivanka Gultom',
            'nick_name' => 'Gia/Nana',
            'birth_town' => 'Bandung',
            'birth_date' => '2019-06-26',
            'origin_school' => '',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '2',
            'parent_name' => 'Bernardus Surya Perdana Gultom',
            'parent_phone' => '081321456542',
            'parent_email' => 'bernardus.gultom@gmail.com',
            'payment_proof' => '1659487848.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-03 00:50:48',
            'updated_at' => '2022-08-03 00:50:48'
        ]);

        TbtkRegistration::create([
            'user_id' => '14',
            'unique_code' => 'DMO0U3SRhbwas6x1loxA',
            'registration_code' => '2324102007',
            'virtual_code' => '8947802324102007',
            'full_name' => 'Nathan Christian',
            'nick_name' => 'Nathan',
            'birth_town' => 'Bandung',
            'birth_date' => '2019-07-03',
            'origin_school' => '',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '2',
            'parent_name' => 'Hanny Meilita Sari',
            'parent_phone' => '08112312400',
            'parent_email' => 'hyukmahoni@gmail.com',
            'payment_proof' => '1659507681.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-03 06:21:21',
            'updated_at' => '2022-08-03 06:21:21'
        ]);

        TbtkRegistration::create([
            'user_id' => '15',
            'unique_code' => 'uyslQGTCLjWt4gukrddw',
            'registration_code' => '2324102008',
            'virtual_code' => '8947802324102008',
            'full_name' => 'Patricia Hedy Betsha Haryanto',
            'nick_name' => 'Patricia',
            'birth_town' => 'Bandung',
            'birth_date' => '2018-03-28',
            'origin_school' => 'Belum Sekolah',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '2',
            'parent_name' => 'Haryanto',
            'parent_phone' => '082128732912',
            'parent_email' => 'Nataliahedy0@gmail.com',
            'payment_proof' => '1660021858.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-09 12:10:58',
            'updated_at' => '2022-08-09 12:10:58'
        ]);

        TbtkRegistration::create([
            'user_id' => '16',
            'unique_code' => 'oTc6ek94z8r1kd3l1OVW',
            'registration_code' => '2324102009',
            'virtual_code' => '8947802324102009',
            'full_name' => 'Clara Felisitas Laverna Tinambunan',
            'nick_name' => 'Clara',
            'birth_town' => 'Bandung',
            'birth_date' => '2019-02-28',
            'origin_school' => '',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '2',
            'parent_name' => 'Edwin Tinambunan',
            'parent_phone' => '082127263641',
            'parent_email' => 'edwintinambunan23@gmail.com',
            'payment_proof' => '1660104708.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-10 11:11:49',
            'updated_at' => '2022-08-10 11:11:49'
        ]);

        TbtkRegistration::create([
            'user_id' => '17',
            'unique_code' => 'J8TQZIVZBLGtmZbhTdK1',
            'registration_code' => '2324101003',
            'virtual_code' => '8947802324101003',
            'full_name' => 'Michael Algio Manuel Lazaro',
            'nick_name' => 'Manuel',
            'birth_town' => 'Purwakarta',
            'birth_date' => '2019-08-25',
            'origin_school' => '',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '1',
            'parent_name' => 'Chiquita',
            'parent_phone' => '081908337090',
            'parent_email' => 'chiquitachristina81@gmail.com',
            'payment_proof' => '1660108232.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-10 12:10:32',
            'updated_at' => '2022-08-12 13:40:59'
        ]);

        TbtkRegistration::create([
            'user_id' => '18',
            'unique_code' => 'urPkmNpDfZlFk0QSfpsU',
            'registration_code' => '2324102010',
            'virtual_code' => '8947802324102010',
            'full_name' => 'Adriel Navin Eightyano Raneke',
            'nick_name' => 'Navin',
            'birth_town' => 'Bandung',
            'birth_date' => '2019-05-09',
            'origin_school' => '',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '2',
            'parent_name' => 'Christine Taneke',
            'parent_phone' => '082116240418',
            'parent_email' => 'taneke54@gmail.com',
            'payment_proof' => '1660109319.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-10 12:28:39',
            'updated_at' => '2022-08-12 13:41:31'
        ]);

        TbtkRegistration::create([
            'user_id' => '19',
            'unique_code' => 'Pk4PiMWqsz9lptPtK5R9',
            'registration_code' => '2324102011',
            'virtual_code' => '8947802324102011',
            'full_name' => 'Elyora Sabatani Nauli',
            'nick_name' => 'Yora',
            'birth_town' => 'Bandung',
            'birth_date' => '2018-12-18',
            'origin_school' => '',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '2',
            'parent_name' => 'Leonardo Sigalingging / Santy Silalahi',
            'parent_phone' => '08156103695',
            'parent_email' => 'ssilalahi@yahoo.com',
            'payment_proof' => '1660109444.jpg',
            'registration_status' => '2',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-10 12:30:44',
            'updated_at' => '2022-08-12 14:09:47'
        ]);

        TbtkRegistration::create([
            'user_id' => '20',
            'unique_code' => 'n3gKebdIPCYqBbOonILv',
            'registration_code' => '2324102012',
            'virtual_code' => '8947802324102012',
            'full_name' => 'Nikolas Adrianto',
            'nick_name' => 'Ian',
            'birth_town' => 'Bandung',
            'birth_date' => '2018-11-17',
            'origin_school' => '',
            'gender' => 'Laki-Laki',
            'register_year' => '2',
            'register_grade' => '2',
            'parent_name' => 'Nana Lusianto',
            'parent_phone' => '0818301759',
            'parent_email' => 'nanalusianto@gmail.com',
            'payment_proof' => '1660462492.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-14 14:34:53',
            'updated_at' => '2022-08-14 14:34:53'
        ]);

        TbtkRegistration::create([
            'user_id' => '21',
            'unique_code' => '6iFv1MhEHm9bEsSYDMyV',
            'registration_code' => '2324102013',
            'virtual_code' => '8947802324102013',
            'full_name' => 'Scholastika Davinia Carissa Putri',
            'nick_name' => 'Davinia',
            'birth_town' => 'Bandung',
            'birth_date' => '2018-09-15',
            'origin_school' => '',
            'gender' => 'Perempuan',
            'register_year' => '2',
            'register_grade' => '2',
            'parent_name' => 'Ignatius Bambang Iswanto',
            'parent_phone' => '081322797703',
            'parent_email' => 'igbamz@gmail.com',
            'payment_proof' => '1660483969.jpg',
            'registration_status' => '1',
            'selection_status' => '0',
            'approval_status' => '0',
            'dapodik_status' => '0',
            'aggrement_status' => '0',
            'payment_status' => '0',
            'uniform_status' => '0',
            'book_status' => '0',
            'created_at' => '2022-08-14 20:32:50',
            'updated_at' => '2022-08-14 20:32:50'
        ]);
    }
}
